#System variables:
isreloading:
isshutdown:
isrunning:
isdebug:
configversion: 2

#Spy variables:
blockversion: true
blockgc: true
blockplugin: true
blockreload: false
blockbaltop: true
blockping: false
spyexecutors: true

#Quest variables:
gold:
diamond:
redstone:
lapis:

#quest player data (this section must be at the end of the file)